### PR TITLE
feat: new script module documentation

### PR DESCRIPTION
**Pull request by SineVector241**
edited @bridge/theme to match others with "View Source Code". Referencing to fetchDefs variable
in fetchDefinition function would be nice to add. IDK where it is though. I also have no idea what resolvePackPath function does. Please fill this out

### CODE REVIEW

**Comment by SineVector241** [comment]
I forgot to add. requestFileSystem function in @bridge/com-mojang example needs finishing. I also have no idea how that works

**Comment by Joelant05** [comment]
This should also aim to close:
- https://github.com/bridge-core/editor/issues/137
- https://github.com/bridge-core/editor/issues/478
- https://github.com/bridge-core/editor/issues/484

**Comment by SineVector241** [comment]
We need a more persistent way of starting the description of each function e.g. in @bridge/themes both `onChange` and `getCurrentMode` have different ways of describing the function. I believe we should all start with **The `Function` function...**

**Comment by solvedDev** [comment]
I believe all of our other reference docs also use different ways to start a section to add variety to the docs but I am fine with going with an uniform style for the technical docs; might make sense

**Review by outercloudstudio — CHANGES_REQUESTED** [review]
Looks good but a few notes on things to be completed:
- `@bridge/command-bar` > `registerAction` doesn't have a code snippet.
- `@compare-versions` > `compareVersions` snippet and returns is incomplete
- `@bridge-fs` > `pathTo`, `unlink`, `writeFile`, `write`, `copyFile`, `copyFileHandle`, `copyFolder`, `copyFolderHandle`, and `directoryHandlesFromGlob` are incomplete
- Functions of `@bridge/import` not complete
- Functions of `@bridge/model-viewer` is not complete
- `@bridge/monaco` > `registerDocumentFormattingEditProvider ` code snippet incomplete
- `@bridge/project` seems to have a lot of function work to do
- `@bridge/reactivity` is incomplete
- `@bridge/tab-actions` is incomplete
- `@bridge/tab` > `register` code snippet is incomplete
- `@bridge/toolbar` is incomplete
- `@bridge/ui` is incomplete

Just one thing that I'll do myself before I merge it is remove the emojis from before `@bridge` because it makes it really hard to read.

**Review by outercloudstudio — APPROVED** [review]

**Pull request merged**
